name: Pytest

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Backend Flask tests
    - name: Build backend environment
      working-directory: ./backend-flask
      run: make build
    
    - name: Run backend tests
      working-directory: ./backend-flask
      run: make test
      env:
        FLASK_ENV: testing
        FLASK_TESTING: true
    
    # Flask Honeypot tests
    - name: Build honeypot environment
      working-directory: ./flask-honeypot
      run: make build
    
    - name: Run honeypot tests
      working-directory: ./flask-honeypot
      run: make test
      env:
        FLASK_ENV: testing
        FLASK_TESTING: true